export const fileTypes = {
    ".html": { icon: "mdi-language-html5", color: "indigo" },
    ".js": { icon: "mdi-nodejs", color: "green" },
    ".json": { icon: "mdi-json", color: "green" },
    ".md": { icon: "mdi-language-markdown", color: "green" },
    ".pdf": { icon: "mdi-pdf-box", color: "primary" },
    ".png": { icon: "mdi-image", color: "blue" },
    ".jpg": { icon: "mdi-image", color: "blue" },
    ".jpeg": { icon: "mdi-image", color: "blue" },
    ".txt": { icon: "mdi-signature-text", color: "grey" },
    ".xls": { icon: "mdi-file-excel-box", color: "teal" },
    ".zip": { icon: "mdi-zip-box", color: "red" },
    ".gif": { icon: "mdi-gif", color: "pink" },
    ".pem": { icon: "mdi-key", color: "green" },
}